### ISSUE TITLE
Was facing this issue while running add-dashboard script

### ISSUE THREAD

**Issue by thangarajbluescape** [Bluescape/helm-charts#34]
@notjames Was facing this issue while running add-dashboard script.
Note: I installed all the pre-requisite .
bluescape-monitoring-dashboards (sre-138/msk-exporter) $ ./add_dashboard $HOME/Downloads/msk.json 30_msk_exporter
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/yaml2json", line 69, in <module>
    yaml_file = open(args.get('<yaml_file>'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '-'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/json2yaml", line 48, in <module>
    json_file = open(args.get('<json_file>'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '-'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/yaml2json", line 69, in <module>
    yaml_file = open(args.get('<yaml_file>'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '-'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/json2yaml", line 48, in <module>
    json_file = open(args.get('<json_file>'), 'r')
FileNotFoundError: [Errno 2] No such file or directory: '-'

**Comment by thangarajbluescape** [comment]
@notjames 
enclta023s-MacBook-Pro [K8s:]:bin $ yaml2json --version
version 1.1.1
enclta023s-MacBook-Pro [K8s:]:bin $ json2yaml --version
version 1.1.1

**Comment by notjames** [comment]
> @notjames
> enclta023s-MacBook-Pro [K8s:]:bin $ yaml2json --version
> version 1.1.1
> enclta023s-MacBook-Pro [K8s:]:bin $ json2yaml --version
> version 1.1.1

lol. Hmm. So this is interesting. You're not using the right `yaml2json` or `json2yaml` scripts. What's more, the ones you're using seem to be python scripts. The ones you should be using are in the ops repo https://github.com/Bluescape/ops/blob/develop/scripts/json2yaml and https://github.com/Bluescape/ops/blob/develop/scripts/yaml2json which are the ones that `add_dashboard` uses
